; Inno Setup script for Helbreath Oblivion
; Generated by make_installer.py

[Setup]
AppName=Helbreath Oblivion
AppVersion=0.2.5
AppPublisher=Helbreath
DefaultDirName={autopf}\Helbreath Oblivion
DefaultGroupName=Helbreath Oblivion
OutputDir=D:\HB Server\Helbreath-Heldenian-Project-Development\tools\InstallerCreator
OutputBaseFilename=HelbreathOblivion_v0.2.5_setup
Compression=lzma2
SolidCompression=yes
SetupIconFile=icono_oblivion.ico
WizardImageFile=columna_izquierda.bmp
WizardSmallImageFile=oblivion_pequeño.bmp
UninstallDisplayIcon={app}\Game_x64_win.exe
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
DisableWelcomePage=no
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Dirs]
Name: "{app}"; Permissions: users-modify

[Files]
Source: "D:\HB Server\Helbreath-Heldenian-Project-Development\Binaries\Game\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\Helbreath Oblivion"; Filename: "{app}\Helbreath Oblivion.exe"
Name: "{autodesktop}\Helbreath Oblivion"; Filename: "{app}\Helbreath Oblivion.exe"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional shortcuts:"

[Run]
Filename: "{app}\Helbreath Oblivion.exe"; Description: "Launch Helbreath Oblivion"; Flags: nowait postinstall skipifsilent
