// Auto-generated by version_gen.py — do not edit manually
#pragma once

namespace hb::version
{

namespace compatibility
{
constexpr int major = 0;
constexpr int minor = 2;
constexpr int patch = 14;
constexpr int build_number = 0;
constexpr const char* stage = "alpha";
constexpr const char* display_version = "0.2.14-alpha";
constexpr const char* full_version = "0.2.14-alpha+build.0";
} // namespace compatibility

namespace server
{
constexpr int major = 0;
constexpr int minor = 1;
constexpr int patch = 24;
constexpr int build_number = 353;
constexpr const char* stage = "alpha";
constexpr const char* display_version = "0.1.24-alpha";
constexpr const char* full_version = "0.1.24-alpha+build.353";
} // namespace server

namespace client
{
constexpr int major = 0;
constexpr int minor = 2;
constexpr int patch = 52;
constexpr int build_number = 458;
constexpr const char* stage = "alpha";
constexpr const char* display_version = "0.2.52-alpha";
constexpr const char* full_version = "0.2.52-alpha+build.458";
} // namespace client

constexpr const char* build_timestamp = "2026-07-30T20:02:08";

} // namespace hb::version
